<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'title' => 'Hoàng Tử Bé',
                'description' => 'Một câu chuyện triết lý nhẹ nhàng cho cả trẻ em và người lớn.',
                'author' => 'Antoine de Saint-Exupéry',
                'type' => 'ebook',
                'category_id' => 1,
                'publication_date' => '1943-04-06',
                'price' => 120000,
                'file_url' => '/ebooks/hoang-tu-be.pdf',
                'image_url' => '/images/hoang-tu-be.jpg',
                'duration' => 0,
                'language' => 'vi',
                'rating' => 4.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Đắc Nhân Tâm',
                'description' => 'Cẩm nang kỹ năng giao tiếp đỉnh cao.',
                'author' => 'Dale Carnegie',
                'type' => 'ebook',
                'category_id' => 2,
                'publication_date' => '1936-01-01',
                'price' => 135000,
                'file_url' => '/ebooks/dac-nhan-tam.pdf',
                'image_url' => '/images/dac-nhan-tam.jpg',
                'duration' => 0,
                'language' => 'vi',
                'rating' => 4.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Nhà Giả Kim',
                'description' => 'Cuốn tiểu thuyết truyền cảm hứng về hành trình theo đuổi giấc mơ.',
                'author' => 'Paulo Coelho',
                'type' => 'ebook',
                'category_id' => 1,
                'publication_date' => '1988-06-15',
                'price' => 145000,
                'file_url' => '/ebooks/nha-gia-kim.pdf',
                'image_url' => '/images/nha-gia-kim.jpg',
                'duration' => 0,
                'language' => 'vi',
                'rating' => 4.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tư Duy Nhanh và Chậm',
                'description' => 'Khám phá cơ chế hoạt động của bộ não con người.',
                'author' => 'Daniel Kahneman',
                'type' => 'ebook',
                'category_id' => 1,
                'publication_date' => '2011-11-01',
                'price' => 160000,
                'file_url' => '/ebooks/tu-duy-nhanh-va-cham.pdf',
                'image_url' => '/images/tu-duy-nhanh-va-cham.jpg',
                'duration' => 0,
                'language' => 'vi',
                'rating' => 4.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Podcast: Thói Quen Tốt',
                'description' => 'Tập podcast về cách hình thành thói quen tích cực mỗi ngày.',
                'author' => 'MindCast Team',
                'type' => 'podcast',
                'category_id' => 2,
                'publication_date' => '2023-01-10',
                'price' => 0,
                'file_url' => '/podcasts/thoi-quen-tot.mp3',
                'image_url' => '/images/podcast-thoi-quen.jpg',
                'duration' => 25,
                'language' => 'vi',
                'rating' => 4.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Podcast: Bí Quyết Tập Trung',
                'description' => 'Làm sao để duy trì sự tập trung trong thời đại xao nhãng.',
                'author' => 'FocusCast',
                'type' => 'podcast',
                'category_id' => 2,
                'publication_date' => '2023-02-15',
                'price' => 0,
                'file_url' => '/podcasts/bi-quyet-tap-trung.mp3',
                'image_url' => '/images/podcast-tap-trung.jpg',
                'duration' => 30,
                'language' => 'vi',
                'rating' => 4.3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Podcast: Kỹ Năng Lắng Nghe',
                'description' => 'Học cách lắng nghe hiệu quả trong công việc và cuộc sống.',
                'author' => 'Kỹ Năng 360',
                'type' => 'podcast',
                'category_id' => 1,
                'publication_date' => '2023-03-01',
                'price' => 0,
                'file_url' => '/podcasts/lang-nghe.mp3',
                'image_url' => '/images/podcast-lang-nghe.jpg',
                'duration' => 22,
                'language' => 'vi',
                'rating' => 4.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ebook: Thiền Trong Công Việc',
                'description' => 'Ứng dụng thiền để giảm stress và tăng hiệu suất.',
                'author' => 'Thích Nhất Hạnh',
                'type' => 'ebook',
                'category_id' => 2,
                'publication_date' => '2005-06-10',
                'price' => 90000,
                'file_url' => '/ebooks/thien-trong-cong-viec.pdf',
                'image_url' => '/images/thien-cong-viec.jpg',
                'duration' => 0,
                'language' => 'vi',
                'rating' => 4.9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Podcast: Nghệ Thuật Giao Tiếp',
                'description' => 'Phát triển kỹ năng giao tiếp qua những tình huống thực tế.',
                'author' => 'Giao Tiếp Pro',
                'type' => 'podcast',
                'category_id' => 2,
                'publication_date' => '2023-04-20',
                'price' => 0,
                'file_url' => '/podcasts/nghe-thuat-giao-tiep.mp3',
                'image_url' => '/images/podcast-giao-tiep.jpg',
                'duration' => 35,
                'language' => 'vi',
                'rating' => 4.2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ebook: 7 Thói Quen Hiệu Quả',
                'description' => 'Khám phá 7 thói quen thay đổi cuộc sống.',
                'author' => 'Stephen R. Covey',
                'type' => 'ebook',
                'category_id' => 2,
                'publication_date' => '1989-08-15',
                'price' => 155000,
                'file_url' => '/ebooks/7-thoi-quen.pdf',
                'image_url' => '/images/7-thoi-quen.jpg',
                'duration' => 0,
                'language' => 'vi',
                'rating' => 4.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Spring whose full phone',
                'description' => 'Quis culpa deserunt cumque veniam iusto sed cum explicabo.',
                'author' => 'Carla Webb',
                'type' => 'ebook',
                'category_id' => 5,
                'publication_date' => '2023-02-20',
                'price' => 144000,
                'file_url' => 'products/product_1.pdf',
                'image_url' => 'products/product_1.jpg',
                'duration' => null,
                'language' => 'vi',
                'rating' => 4.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Speak think since pass',
                'description' => 'Laborum atque delectus quis quis ad vero quo.',
                'author' => 'Edward Fields',
                'type' => 'podcast',
                'category_id' => 2,
                'publication_date' => '2022-01-30',
                'price' => 0,
                'file_url' => 'products/product_2.mp3',
                'image_url' => 'products/product_2.jpg',
                'duration' => 2604,
                'language' => 'vi',
                'rating' => 3.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Nearly street nation mind',
                'description' => 'Quia deserunt aut voluptas minima ut deleniti cum deserunt velit.',
                'author' => 'David Ferguson',
                'type' => 'ebook',
                'category_id' => 3,
                'publication_date' => '2022-07-12',
                'price' => 80000,
                'file_url' => 'products/product_3.pdf',
                'image_url' => 'products/product_3.jpg',
                'duration' => null,
                'language' => 'vi',
                'rating' => 4.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Begin soldier need baby',
                'description' => 'Aut molestias maxime error vel dolorum ea non sunt.',
                'author' => 'Julie Kennedy',
                'type' => 'ebook',
                'category_id' => 1,
                'publication_date' => '2023-04-25',
                'price' => 72000,
                'file_url' => 'products/product_4.pdf',
                'image_url' => 'products/product_4.jpg',
                'duration' => null,
                'language' => 'vi',
                'rating' => 4.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Party economic speech',
                'description' => 'Excepturi consequatur et eveniet assumenda qui aut.',
                'author' => 'Ryan Blair',
                'type' => 'podcast',
                'category_id' => 2,
                'publication_date' => '2023-06-01',
                'price' => 0,
                'file_url' => 'products/product_5.mp3',
                'image_url' => 'products/product_5.jpg',
                'duration' => 2690,
                'language' => 'vi',
                'rating' => 4.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Seat raise memory together',
                'description' => 'Beatae sed aut et.',
                'author' => 'Karen Freeman',
                'type' => 'ebook',
                'category_id' => 1,
                'publication_date' => '2024-01-09',
                'price' => 144000,
                'file_url' => 'products/product_6.pdf',
                'image_url' => 'products/product_6.jpg',
                'duration' => null,
                'language' => 'vi',
                'rating' => 3.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Hand final cause',
                'description' => 'Eius error officia voluptatem.',
                'author' => 'Joseph Allen',
                'type' => 'ebook',
                'category_id' => 1,
                'publication_date' => '2024-02-28',
                'price' => 49000,
                'file_url' => 'products/product_7.pdf',
                'image_url' => 'products/product_7.jpg',
                'duration' => null,
                'language' => 'vi',
                'rating' => 4.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Difference phone born',
                'description' => 'Voluptatibus omnis dolore dolorum mollitia in ducimus.',
                'author' => 'Barbara Cook',
                'type' => 'podcast',
                'category_id' => 2,
                'publication_date' => '2023-08-20',
                'price' => 0,
                'file_url' => 'products/product_8.mp3',
                'image_url' => 'products/product_8.jpg',
                'duration' => 1030,
                'language' => 'vi',
                'rating' => 4.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ball agree soldier chance',
                'description' => 'Aliquid in repellat maiores veritatis.',
                'author' => 'Cheryl Hicks',
                'type' => 'ebook',
                'category_id' => 5,
                'publication_date' => '2022-11-11',
                'price' => 189000,
                'file_url' => 'products/product_9.pdf',
                'image_url' => 'products/product_9.jpg',
                'duration' => null,
                'language' => 'vi',
                'rating' => 4.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Everything we yet carry',
                'description' => 'Distinctio officia atque libero ex asperiores modi.',
                'author' => 'Robert Armstrong',
                'type' => 'ebook',
                'category_id' => 1,
                'publication_date' => '2023-09-10',
                'price' => 51000,
                'file_url' => 'products/product_10.pdf',
                'image_url' => 'products/product_10.jpg',
                'duration' => null,
                'language' => 'vi',
                'rating' => 4.3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Family buy general however',
                'description' => 'Aut tempore et sint et aut.',
                'author' => 'Margaret Williams',
                'type' => 'podcast',
                'category_id' => 4,
                'publication_date' => '2023-05-15',
                'price' => 0,
                'file_url' => 'products/product_11.mp3',
                'image_url' => 'products/product_11.jpg',
                'duration' => 2586,
                'language' => 'vi',
                'rating' => 4.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Eye their energy forget',
                'description' => 'Sunt exercitationem in quam saepe.',
                'author' => 'Nancy Martinez',
                'type' => 'ebook',
                'category_id' => 1,
                'publication_date' => '2023-10-05',
                'price' => 69000,
                'file_url' => 'products/product_12.pdf',
                'image_url' => 'products/product_12.jpg',
                'duration' => null,
                'language' => 'vi',
                'rating' => 4.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Way seem ask around',
                'description' => 'Quo autem sit ut molestiae animi deserunt.',
                'author' => 'Daniel Rogers',
                'type' => 'ebook',
                'category_id' => 3,
                'publication_date' => '2022-03-14',
                'price' => 52000,
                'file_url' => 'products/product_13.pdf',
                'image_url' => 'products/product_13.jpg',
                'duration' => null,
                'language' => 'vi',
                'rating' => 4.1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Firm early form teacher',
                'description' => 'Non corporis exercitationem dolorem.',
                'author' => 'Ralph Hall',
                'type' => 'ebook',
                'category_id' => 3,
                'publication_date' => '2021-08-19',
                'price' => 55000,
                'file_url' => 'products/product_14.pdf',
                'image_url' => 'products/product_14.jpg',
                'duration' => null,
                'language' => 'vi',
                'rating' => 4.9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Out war support name',
                'description' => 'Aut aut est amet explicabo molestiae.',
                'author' => 'Betty Jackson',
                'type' => 'podcast',
                'category_id' => 2,
                'publication_date' => '2023-12-13',
                'price' => 0,
                'file_url' => 'products/product_15.mp3',
                'image_url' => 'products/product_15.jpg',
                'duration' => 3272,
                'language' => 'vi',
                'rating' => 4.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Concern close already',
                'description' => 'Ratione ullam est quam eveniet.',
                'author' => 'Doris Clark',
                'type' => 'podcast',
                'category_id' => 2,
                'publication_date' => '2022-09-25',
                'price' => 0,
                'file_url' => 'products/product_16.mp3',
                'image_url' => 'products/product_16.jpg',
                'duration' => 1168,
                'language' => 'vi',
                'rating' => 4.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Girl floor enter old',
                'description' => 'Consequuntur quam in doloremque.',
                'author' => 'Josephine Taylor',
                'type' => 'podcast',
                'category_id' => 4,
                'publication_date' => '2022-06-10',
                'price' => 0,
                'file_url' => 'products/product_17.mp3',
                'image_url' => 'products/product_17.jpg',
                'duration' => 2332,
                'language' => 'vi',
                'rating' => 4.3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Right contain serve',
                'description' => 'Rerum reiciendis suscipit laboriosam.',
                'author' => 'Albert Garcia',
                'type' => 'ebook',
                'category_id' => 6,
                'publication_date' => '2024-02-17',
                'price' => 69000,
                'file_url' => 'products/product_18.pdf',
                'image_url' => 'products/product_18.jpg',
                'duration' => null,
                'language' => 'vi',
                'rating' => 4.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Total discuss yeah feeling',
                'description' => 'Quisquam occaecati quae.',
                'author' => 'Martha Nelson',
                'type' => 'podcast',
                'category_id' => 6,
                'publication_date' => '2023-07-30',
                'price' => 0,
                'file_url' => 'products/product_19.mp3',
                'image_url' => 'products/product_19.jpg',
                'duration' => 1140,
                'language' => 'vi',
                'rating' => 4.2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Even may economic most',
                'description' => 'Quis minima sit labore.',
                'author' => 'Henry Lee',
                'type' => 'ebook',
                'category_id' => 5,
                'publication_date' => '2023-11-01',
                'price' => 136000,
                'file_url' => 'products/product_20.pdf',
                'image_url' => 'products/product_20.jpg',
                'duration' => null,
                'language' => 'vi',
                'rating' => 4.1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
