<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'title' => 'Hoàng Tử Bé',
                'description' => 'Một câu chuyện triết lý nhẹ nhàng cho cả trẻ em và người lớn.',
                'author' => 'Antoine de Saint-Exupéry',
                'type' => 'ebook',
                'category_id' => 1,
                'publication_date' => '1943-04-06',
                'price' => 120000,
                'file_url' => '/ebooks/hoang-tu-be.pdf',
                'image_url' => '/images/hoang-tu-be.jpg',
                'duration' => 0,
                'language' => 'vi',
                'rating' => 4.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Đắc Nhân Tâm',
                'description' => 'Cẩm nang kỹ năng giao tiếp đỉnh cao.',
                'author' => 'Dale Carnegie',
                'type' => 'ebook',
                'category_id' => 2,
                'publication_date' => '1936-01-01',
                'price' => 135000,
                'file_url' => '/ebooks/dac-nhan-tam.pdf',
                'image_url' => '/images/dac-nhan-tam.jpg',
                'duration' => 0,
                'language' => 'vi',
                'rating' => 4.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Nhà Giả Kim',
                'description' => 'Cuốn tiểu thuyết truyền cảm hứng về hành trình theo đuổi giấc mơ.',
                'author' => 'Paulo Coelho',
                'type' => 'ebook',
                'category_id' => 1,
                'publication_date' => '1988-06-15',
                'price' => 145000,
                'file_url' => '/ebooks/nha-gia-kim.pdf',
                'image_url' => '/images/nha-gia-kim.jpg',
                'duration' => 0,
                'language' => 'vi',
                'rating' => 4.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tư Duy Nhanh và Chậm',
                'description' => 'Khám phá cơ chế hoạt động của bộ não con người.',
                'author' => 'Daniel Kahneman',
                'type' => 'ebook',
                'category_id' => 1,
                'publication_date' => '2011-11-01',
                'price' => 160000,
                'file_url' => '/ebooks/tu-duy-nhanh-va-cham.pdf',
                'image_url' => '/images/tu-duy-nhanh-va-cham.jpg',
                'duration' => 0,
                'language' => 'vi',
                'rating' => 4.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Podcast: Thói Quen Tốt',
                'description' => 'Tập podcast về cách hình thành thói quen tích cực mỗi ngày.',
                'author' => 'MindCast Team',
                'type' => 'podcast',
                'category_id' => 2,
                'publication_date' => '2023-01-10',
                'price' => 0,
                'file_url' => '/podcasts/thoi-quen-tot.mp3',
                'image_url' => '/images/podcast-thoi-quen.jpg',
                'duration' => 25,
                'language' => 'vi',
                'rating' => 4.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Podcast: Bí Quyết Tập Trung',
                'description' => 'Làm sao để duy trì sự tập trung trong thời đại xao nhãng.',
                'author' => 'FocusCast',
                'type' => 'podcast',
                'category_id' => 2,
                'publication_date' => '2023-02-15',
                'price' => 0,
                'file_url' => '/podcasts/bi-quyet-tap-trung.mp3',
                'image_url' => '/images/podcast-tap-trung.jpg',
                'duration' => 30,
                'language' => 'vi',
                'rating' => 4.3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Podcast: Kỹ Năng Lắng Nghe',
                'description' => 'Học cách lắng nghe hiệu quả trong công việc và cuộc sống.',
                'author' => 'Kỹ Năng 360',
                'type' => 'podcast',
                'category_id' => 1,
                'publication_date' => '2023-03-01',
                'price' => 0,
                'file_url' => '/podcasts/lang-nghe.mp3',
                'image_url' => '/images/podcast-lang-nghe.jpg',
                'duration' => 22,
                'language' => 'vi',
                'rating' => 4.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ebook: Thiền Trong Công Việc',
                'description' => 'Ứng dụng thiền để giảm stress và tăng hiệu suất.',
                'author' => 'Thích Nhất Hạnh',
                'type' => 'ebook',
                'category_id' => 2,
                'publication_date' => '2005-06-10',
                'price' => 90000,
                'file_url' => '/ebooks/thien-trong-cong-viec.pdf',
                'image_url' => '/images/thien-cong-viec.jpg',
                'duration' => 0,
                'language' => 'vi',
                'rating' => 4.9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Podcast: Nghệ Thuật Giao Tiếp',
                'description' => 'Phát triển kỹ năng giao tiếp qua những tình huống thực tế.',
                'author' => 'Giao Tiếp Pro',
                'type' => 'podcast',
                'category_id' => 2,
                'publication_date' => '2023-04-20',
                'price' => 0,
                'file_url' => '/podcasts/nghe-thuat-giao-tiep.mp3',
                'image_url' => '/images/podcast-giao-tiep.jpg',
                'duration' => 35,
                'language' => 'vi',
                'rating' => 4.2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ebook: 7 Thói Quen Hiệu Quả',
                'description' => 'Khám phá 7 thói quen thay đổi cuộc sống.',
                'author' => 'Stephen R. Covey',
                'type' => 'ebook',
                'category_id' => 2,
                'publication_date' => '1989-08-15',
                'price' => 155000,
                'file_url' => '/ebooks/7-thoi-quen.pdf',
                'image_url' => '/images/7-thoi-quen.jpg',
                'duration' => 0,
                'language' => 'vi',
                'rating' => 4.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
